kegiatan/urls.py
from django.urls import path

from . import views

app_name = 'kegiatan'

urlpatterns = [
    path('', views.index, name='index'),
    path('tambah-kegiatan/', views.tambah_kegiatan, name='tambah_kegiatan'),
    path('tambah-peserta/<int:pk>/', views.tambah_peserta, name='tambah_peserta'),
    path('peserta/<int:pk>/', views.daftar_peserta, name='daftar_peserta')
]

main/urls.py
from django.urls import path

from . import views

app_name = 'main'

urlpatterns = [
    path('', views.home, name='home'),
    path('contact', views.contact, name='contact'),
]

matkul/urls.py
from django.urls import path

from . import views

app_name = 'matkul'

urlpatterns = [
    path('', views.home, name='home'),
    path('tambah', views.tambah, name='tambah'),
    path('hapus/<int:delete_id>', views.hapus, name='hapus'),
    path('detail/<int:delete_id>', views.detail, name='detail')
]

story1/urls.py
from django.urls import path

from . import views

app_name = 'story1'

urlpatterns = [
    path('profile', views.profile, name='profile'),
]

story4ppw/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('', include('story1.urls')),
    path('matkul/', include('matkul.urls'), name='matkul'),
    path('kegiatan/', include('kegiatan.urls'), name='kegiatan'),
]

kegiatan/models.py
from django.db import models

class Kegiatan(models.Model):
    name = models.CharField(max_length=50)
    deskripsi = models.CharField(max_length=250)

class Peserta(models.Model):
    kegiatan = models.ForeignKey(Kegiatan, on_delete=models.CASCADE, related_name='peserta')
    name = models.CharField(max_length=50)

main/models.py
from django.db import models

# Create your models here.

matkul/models.py
from django.db import models

class MataKuliah(models.Model):
    nama = models.CharField(max_length=30)
    dosen = models.CharField(max_length=30)
    sks = models.IntegerField()
    desc = models.CharField(max_length=100)
    semester = models.CharField(max_length=15)
    kelas = models.CharField(max_length=15)

    def __str__(self):
        return "{}.{}".format(self.id, self.nama)

story1/models.py
from django.db import models

# Create your models here.

matkul/forms.py
from django import forms
from .models import MataKuliah

class FormMataKuliah(forms.ModelForm):
    class Meta:
        model = MataKuliah
        fields = [
            'nama',
            'dosen',
            'sks',
            'desc',
            'semester',
            'kelas'
        ]

    

kegiatan/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponseBadRequest
from .models import Kegiatan, Peserta

def index(request):
    response = {
        'title' : 'Kegiatan',
        'daftar_kegiatan' : Kegiatan.objects.all()
    }
    return render(request, 'kegiatan/index.html', response)

def tambah_kegiatan(request):    
    if (request.method == 'POST'):
        try:
            kegiatan_baru = Kegiatan(name=request.POST['kegiatan_name'],deskripsi=request.POST['deskripsi'])
            kegiatan_baru.save()
        except:
            return HttpResponseBadRequest('Kegiatan instance not found')
    return redirect('kegiatan:index')

def tambah_peserta(request, pk=None):
    if (request.method == 'POST'):
        kegiatan = Kegiatan.objects.get(pk=pk)
        name = request.POST['nama_peserta']
        peserta = Peserta(name=name, kegiatan=kegiatan)
        peserta.save()
        return redirect(f'/kegiatan/peserta/{kegiatan.pk}/')
    else:
        return redirect('kegiatan:index')

def daftar_peserta(request, pk=None):
    response = {
        'title' : 'Detail Kegiatan',
        'kegiatan' : Kegiatan.objects.get(pk=pk)
    }
    return render(request, 'kegiatan/peserta.html', response)

main/views.py
from django.shortcuts import render


def home(request):
    return render(request, 'main/home.html')

def contact(request):
    return render(request, 'main/contact.html')

matkul/views.py
from django.shortcuts import render, redirect
from .models import MataKuliah
from .forms import FormMataKuliah

def home(request):
    semua_matkul = MataKuliah.objects.all()
    response = {
        'title' : 'List Mata Kuliah',
        'semua_matkul' : semua_matkul
    }

    return render(request, 'matkul/home.html', response)

def tambah(request):
    form_tambah = FormMataKuliah(request.POST or None)

    if request.method == 'POST':
        if form_tambah.is_valid():
            form_tambah.save()
            return redirect('matkul:home')

    response = {
        'title' : 'Tambah Mata Kuliah Baru',
        'form_tambah' : form_tambah
    }

    return render(request, 'matkul/new.html', response)

def detail(request, delete_id):
    detail_matkul = MataKuliah.objects.get(id=delete_id)
    response = {
        'title' : 'Detail Mata Kuliah',
        'detail_matkul' : detail_matkul
    }

    return render(request, 'matkul/detail.html', response)

def hapus(request, delete_id):
    MataKuliah.objects.filter(id = delete_id).delete()
    return redirect('matkul:home')

story1/views.py
from django.shortcuts import render


def profile(request):
    return render(request, 'story1/profile.html')

kegiatan/templates/kegiatan/index.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
<title>{{title}}</title>
{% endblock meta %}

{% block content %}
<div class="contact">
    <div class="container">
        <div class="row mb-5 text-center">
            <div class="col">
                <h1>{{title}}</h1>
            </div>
        </div>
    </div>
    <div class="card">
      <div class="card-header">Tambah Kegiatan</div>
        <div class="card-body">
          <form method='POST' action='/kegiatan/tambah-kegiatan/'>
            {% csrf_token %}
            <div class="form-group">
              <label>Nama Kegiatan</label>
              <input type="text" class="form-control" name='kegiatan_name' required>
              <label>Deskripsi Kegiatan</label>
              <input type="text" class="form-control" name='deskripsi'>
            </div>
            <button type="submit" class="btn btn-success">Submit</button>
          </form>
        </div>
      </div>
    <div class="row">
        <div class="col">
            <div class="d-flex flex-wrap justify-content-center">
                {% for kegiatan in daftar_kegiatan %}
                  <div class="card kegiatan m-3" style="color: black;">
                    <div class="card-body d-flex flex-column justify-content-between">
                      <h5 class="card-title" style="color: white;">{{ kegiatan.name }}</h5>
                      <h6 class="card-subtitle mb-2 text-muted">Peserta:</h6>
                      <ul class="list-group list-group-flush" style="color: white;">
                        {% if kegiatan.peserta.all|length < 1 %}
                          Tidak ada peserta
                        {% else %}
                        {% for peserta in kegiatan.peserta.all %}
                            {% if forloop.counter < 4 %}
                                {{ peserta.name }}<br/>
                            {% endif %}
                        {% endfor %}
                        {% endif %}
                      </ul>
                      <a class="btn" href="{% url 'kegiatan:daftar_peserta' kegiatan.pk %}">Detail</a>
                    </div>
                  </div>
                {% endfor %}
              </div>
        </div>
    </div>
    
</div>
{% endblock content %}

kegiatan/templates/kegiatan/peserta.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
<title>{{title}}</title>
{% endblock meta %}

{% block content %}
<div class="contact">
    <div class="container">
        <div class="row mb-5 text-center">
            <div class="col">
                <h1>{{title}} {{kegiatan.name}}</h1>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col">
            <h3 style="color: green;">Deskripsi</h3>
            {% if kegiatan.deskripsi %}
            <p>{{ kegiatan.deskripsi }}</p>
            {% else %}
            <p>Tidak ada deskripsi</p>
            {% endif %}
            <h3 style="color: green;">Daftar Peserta</h3>
            {% if kegiatan.peserta.all|length == 0 %}
                <p>Tidak ada peserta</p>
            {% else %}
            <table class="table table-striped">
                <tbody>
                    {% for peserta in kegiatan.peserta.all %}
                    <tr>
                        <td>{{ peserta.name }}</td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        {% endif %}
        </div>
    </div>
    <div>
        <form method='POST' action='/kegiatan/tambah-peserta/{{ kegiatan.pk }}/'>
            {% csrf_token %}
            <div class="form-group">
                <label>Pengen ikut? Tambah Nama Anda</label>
                <input type="text" class="form-control" name='nama_peserta' required>
            </div>
            <button type="submit" class="btn btn-success">Daftar</button>
        </form>
    </div>
</div>
{% endblock content %}

main/templates/main/contact.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
<title>Contact Me</title>
{% endblock meta %}

{% block content %}
<section id="contact" class="contact">
  <div class="container">
      <div class="row mb-5 text-center">
          <div class="col">
              <h1>Contact Me</h1>
          </div>
      </div>

<div class="row">
  <div class="col">
    <form class="form mx-5">
      <div class="row">
        <div class="col">
          <div class="form-group">
            <label for="Name">Name</label>
            <input type="text" class="form-control" id="Name">
          </div>
        </div>
        <div class="col">
          <div class="form-group">
            <label for="Email">Email</label>
            <input type="text" class="form-control" id="Email">
          </div>
        </div>
      </div>

      <div class="row">
        <div class="col">
          <div class="form-group">
            <label for="Subject">Subject</label>
            <input type="text" class="form-control" id="Subject">
          </div>
          <div class="form-group">
            <label for="Message">Message</label>
            <textarea name="Message" class="form-control" id="Message"></textarea>
          </div>
        </div>
      </div>
      <div class="form-group">
        <button type="button" class="btn btn-outline-secondary btn-lg">SEND</button>
      </div>
      
    </form>
  </div>
</div>
</div>
</section>
{% endblock content %}

main/templates/main/home.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
<title>Hello, world!</title>
{% endblock meta %}

{% block content %}
  <header class="header">
      <div class="overlay"></div>
      <div class="container">
          <div class="description ">
              <h2>Hello, I am</h2><br>
              <h1>Muhammad Urwatil <mark>Wutsqo</mark></h1>
              <p>Computer science student who are currently learning web design and programming</p><br>
              <a href="{% url 'main:contact' %}"><button class="btn btn-outline-secondary btn-lg">Contact me</button></a>
              
          </div>
      </div>   
  </header>

  <div class="about" id="about"> 
      <div class="container">
          <div class="row">
              <div class="col-lg-4 col-md-4 col-sm-12">
                  <h1>About me</h1>
              </div>
              <div class="col-lg-8 col-md-8 col-sm-12 desc">
                  <h3>Education</h3>
                  <p>2016 - 2019 SMAN 1 Sumatera Barat<br>
                  2019 - 2023 Computer Science - Universitas Indonesia</p>
                  <a href="{% url 'story1:profile' %}"><button class="btn btn-outline-secondary btn-lg">See detailed profile</button></a>
              </div>
          </div>
      </div>
  </div>

  <!-- portfolio -->
  <div class="portfolio" id="portfolio">
      <h1 class="text-center">Projects</h1>
      <div class="container">
          <div class="row">
              <div class="col-lg-4 col-md-4 col-sm-12">
                  <img src="https://news.blr.com/app/uploads/sites/3/2019/10/Team-project.jpg" class="img-fluid">
                  <p style="text-align: center;"><a href="#" style="color: aliceblue;">Project One</a></p>
              </div>
              <div class="col-lg-4 col-md-4 col-sm-12">
                  <img src="https://www.bounteous.com/sites/default/files/styles/default/public/insights/2019-10/previews/20191003_blog_scoping_a_data_science_project_in_a_smarter_way_website.png?itok=TKaHtpX-" class="img-fluid">
                  <p style="text-align: center;"><a href="#" style="color: aliceblue;">Project Two</a></p>
              </div>
              <div class="col-lg-4 col-md-4 col-sm-12">
                  <img src="https://news.blr.com/app/uploads/sites/3/2019/10/Team-project.jpg" class="img-fluid">
                  <p style="text-align: center;"><a href="#" style="color: aliceblue;">Project Three</a></p>
          </div>
      </div>
  </div>
  
  <!-- Footer -->
  <div class="contact-cv">
      <div class="container">
          <div class="row">
              <div class="col-lg-6 col-md-6 col-sm-12" style="text-align: center;">
                  <a href="{% url 'main:contact' %}"><button class="btn btn-outline-secondary btn-lg">Contact me</button></a>
              </div>
              <div class="col-lg-6 col-md-6 col-sm-12" style="text-align: center;">
                  <a href="https://cv.wutsqo.wtf" target="_blank"><button class="btn btn-outline-secondary btn-lg">Download My CV</button></a>
              </div>
          </div>
      </div>
  </div>
{% endblock content %}

matkul/templates/matkul/detail.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
<title>{{title}}</title>
{% endblock meta %}

{% block content %}
<div class="contact">
    <div class="container">
        <div class="row mb-5 text-center">
            <div class="col">
                <h1>{{title}} {{detail_matkul.nama}}</h1>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col">
            <div class="table-responsive-lg">
                <table class="table table-striped">
                <tr>
                    <th scope="col">Mata Kuliah</th>
                    <td>{{detail_matkul.nama}}</td>
                </tr>
                <tr>
                    <th scope="col">Dosen Pengajar</th>
                    <td>{{detail_matkul.dosen}}</td>
                </tr>
                <tr>
                    <th scope="col">Deskripsi</th>
                    <td>{{detail_matkul.desc}}</td>
                </tr>
                <tr>
                    <th scope="col">Jumlah SKS</th>
                    <td>{{detail_matkul.sks}}</td>
                </tr>
                <tr>
                    <th scope="col">Ruang Kelas</th>
                    <td>{{detail_matkul.kelas}}</td>
                </tr>
                <tr>
                    <th scope="col">Semester Tahun</th>
                    <td>{{detail_matkul.semester}}</td>
                </tr>
                
            </table>
        </div>
    </div>
</div>
{% endblock content %}

matkul/templates/matkul/home.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
<title>{{title}}</title>
{% endblock meta %}

{% block content %}
<div class="contact">
    <div class="container">
        <div class="row mb-5 text-center">
            <div class="col">
                <h1>{{title}}</h1>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col">
            <div class="table-responsive-lg">
                <table class="table table-stripped">
                    <thead>
                        <tr>
                            <th scope="col">ID</th>
                            <th scope="col">Mata Kuliah</th>
                            <th scope="col">Detail</th>
                            <th scope="col">Hapus</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for matkul in semua_matkul%}
                        <tr>
                            <th scope="row">{{forloop.counter}}</th>
                            <td>{{matkul.nama}}</td>
                            <td><a class="btn" href="{% url 'matkul:detail' matkul.id %}">Detail</a></td>
                            <td><a class="btn btn-danger" href="{% url 'matkul:hapus' matkul.id%}">Hapus</a></td>
                            </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
            <a class="btn btn-primary" href="{% url 'matkul:tambah' %}">Tambah</a>
        </div>
    </div>
</div>
{% endblock content %}

matkul/templates/matkul/new.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
<title>{{title}}</title>
{% endblock meta %}

{% block content %}
<div class="contact">
    <div class="container">
        <div class="row mb-5 text-center">
            <div class="col">
                <h1>{{title}}</h1>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col">
            <form method="POST">
                {% csrf_token %}
                <table>
                    {{form_tambah.as_table}}
                </table>
                <button type="submit">Tambahkan</button>
            </form>
        </div>
    </div>
</div>
{% endblock content %}

story1/templates/story1/profile.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
<title>Hello, world!</title>
{% endblock meta %}

{% block content %}
<div class="profile">
  <div class="container">
    <div class="row">
      <!--
      <div class="col-lg-4 col-md-4 col-sm-12">
        <img src="{% static 'img/profile.jpg' %}" alt="profile">
      </div>
    -->
      <div class="col-lg-8 col-md-8 col-sm-12">
        <h3 style="color: green;">Hello there, Welcome to my profile!</h3>
        <p><strong>Name</strong>:<br>
          Muhammad Urwatil Wutsqo</p>
          <p><strong>NPM</strong>:<br>
          1906351101</p>
          <p><strong>Education</strong>:<br>
          Computer Science - Universitas Indonesia<br>
          SMAN 1 Sumatera Barat</p>
          <p><strong>Hobby</strong>:<br>
          Learn new things<br>
          Reading<br>
          Playing valorant</p>
          <p><strong>Contact/Social Media</strong>:<br>
          <a href="https://line.me/ti/p/~wutsqoo">Line</a> (id: wutsqoo)<br>
          <a href="mailto:urwatilwutsqo16@gmail.com">Email</a><br>
          <a href="https://www.linkedin.com/in/wutsqo">Linkedin</a><br>
          <a href="https://steamcommunity.com/id/schromage">Steam</a></p>
          <hr>
          <p>こんにちは！私はウツコです。インドネシア出身です。コンピュータサイエンスを勉強しています。</p>
      </div>
    </div>
  </div>
</div>
{% endblock content %}

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">

  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>
  
  <link rel="stylesheet" href="{% static 'css/style.css' %}">
  {% block meta %}
  {% endblock meta %}
</head>

<body class="body">
  <!-- navbar -->  
  <nav class="navbar navbar-expand-lg fixed-top"> 
    <a class="navbar-brand" href="{% url 'main:home' %}">
        <img src="{% static 'img/logo.svg' %}" alt="Logo" style="width:40px;">
    </a> 
    <a class="navbar-brand" href="{% url 'main:home' %}">Home</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">  
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse " id="navbarSupportedContent">
        <ul class="navbar-nav mr-4">
            <li class="nav-item">
                <a class="nav-link" data-value="about" href="{% url 'main:home' %}#about">About</a>
            </li>  
            <li class="nav-item">
                <a class="nav-link" data-value="portfolio"href="{% url 'main:home' %}#portfolio">Projects</a>    
            </li>  
            <li class="nav-item"> 
                <a class="nav-link" data-value="contact" href="{% url 'main:contact' %}">Contact</a>
            </li>
            <li>
                <a class="nav-link" data-value="matkul" href="{% url 'matkul:home' %}">Matkul</a>
            </li>
            <li>
              <a class="nav-link" data-value="matkul" href="{% url 'kegiatan:index' %}">Kegiatan</a>
          </li>  
        </ul> 
    </div>
  </nav>

  <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>
       
  <script type="text/javascript" src="{% static 'js/main.js' %}"></script>
</body>
  {% block content %}
  {% endblock content %}
</html>